#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(5, "answers-syscall.txt")
def test_answers():
    # just a simple sanity check, will be graded manually
    check_answers("answers-syscall.txt")

@test(10, "randomtest 1")
def test_randomtest():
    r.run_qemu(shell_script([
        'randomtest 555'
    ]))
    r.match('40')
    r.match('69')
    r.match('74')
    r.match('3')
    r.match('60')
    r.match('1')
    r.match('10')
    r.match('39')
    r.match('96')
    r.match('49')

@test(10, "randomtest 2")
def test_randomtest():
    r.run_qemu(shell_script([
        'randomtest 101'
    ]))
    r.match('42')
    r.match('79')
    r.match('84')
    r.match('53')
    r.match('94')
    r.match('79')
    r.match('44')
    r.match('9')
    r.match('10')
    r.match('19')

@test(10, "randomtest 3")
def test_randomtest():
    r.run_qemu(shell_script([
        'randomtest 43'
    ]))
    r.match('24')
    r.match('33')
    r.match('62')
    r.match('63')
    r.match('88')
    r.match('1')
    r.match('26')
    r.match('59')
    r.match('52')
    r.match('89')

@test(8, "trace 32 grep")
def test_trace_32_grep():
    r.run_qemu(shell_script([
        'trace 32 grep hello README'
    ]))
    r.match('^\\d+: syscall read -> 1023')
    r.match('^\\d+: syscall read -> 961')
    r.match('^\\d+: syscall read -> 321')
    r.match('^\\d+: syscall read -> 0')

@test(8, "trace all grep")
def test_trace_all_grep():
    r.run_qemu(shell_script([
        'trace 2147483647 grep hello README'
    ]))
    r.match('^\\d+: syscall trace -> 0')
    r.match('^\\d+: syscall exec -> 3')
    r.match('^\\d+: syscall open -> 3')
    r.match('^\\d+: syscall read -> 1023')
    r.match('^\\d+: syscall read -> 961')
    r.match('^\\d+: syscall read -> 321')
    r.match('^\\d+: syscall read -> 0')
    r.match('^\\d+: syscall close -> 0')

@test(8, "trace nothing")
def test_trace_nothing():
    r.run_qemu(shell_script([
        'grep hello README'
    ]))
    r.match(no=[".* syscall .*"])

#@test(5, "trace children")
#def test_trace_children():
#    r.run_qemu(shell_script([
#        'trace 2 usertests forkforkfork'
#    ]))
#    r.match('3: syscall fork -> 4')
#    r.match('^5: syscall fork -> \\d+')
#    r.match('^6: syscall fork -> \\d+')
#    r.match('^\\d+: syscall fork -> -1')
#    r.match('^ALL TESTS PASSED')

@test(33, "sysinfotest")
def test_sysinfotest():
    r.run_qemu(shell_script([
        'sysinfotest'
    ]))
    r.match('^sysinfotest: OK', no=[".* FAIL .*"])

@test(1, "time")
def test_time():
    check_time()

run_tests()



